### PR TITLE
Revert "Coin Flip Modal"

### PR DESCRIPTION
**Pull request by johnanvik**
Reverting change as it broke production.

### CODE REVIEW

**Comment by vincentcote87** [comment]
Was @sscullen not able to run npm install due-radial-progress on the server side to fix the build?

**Comment by johnanvik** [comment]
I haven't heard from him. As it has been down for several days I thought it better to revert the change until Shawn can address this.

**Comment by johnanvik** [comment]
Can you please open an issue assigned to @sscullen that has the details of what needs to be done? That way we can track it.

**Comment by johnanvik** [comment]
Closing, as will need to revert the revert :-).

**Pull request closed without merging**
