### PR TITLE
Added documentation to all classes.

### LINKED ISSUE #262: Documentation
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Have the classes, especially the Vue components be documented. 
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by JaceRiehl**
Fixes #262

#### Overview of changes

- Added Documentation to the classes.

Reviewer: @johnanvik

### CODE REVIEW

**Comment by JaceRiehl** [comment]
I'm trying to figure out why the build is failing. I checked and the master branch is doing the same thing when I run the tests.

**Comment by JaceRiehl** [comment]
I had to reset to a previous build that was working on the documentation branch. I'm not sure why removing those two console.log statements threw an error.

**Comment by JaceRiehl** [comment]
I ran npm run test with a lot of previous versions on the master branch and they all fail but it doesn't show the reason as to why. This is likely correlated to the problem that I was having. This might be worth looking into.

**Comment by johnanvik** [comment]
It seems like the build is succeeding. I  grabbed the most recent `master` branch and ran `npm test` fine. I'm not sure what you are seeing.

Accepting PR.

**Pull request merged**
