### PR TITLE
Themes

### LINKED ISSUE #68: Themes
Allowing theming of the interface so players can choose the look.

### PR DESCRIPTION
**Pull request by JaceRiehl**
Fixes #68 

#### Overview of changes

- Adds themes and a theme picker to the game. 
- This is going to cause a slight UI problem when the PR #397 because of the modified tip box.
- Don't commit this quite yet, I'll fix the themes to work with the new UI
Reviewer: @johnanvik

### CODE REVIEW

**Comment by johnanvik** [comment]
@JaceRiehl Can you handle the conflicts? I was trying but wasn't quite sure what stays and what goes.

**Comment by johnanvik** [comment]
Let's get rid of some of the redundant wording. What do you think?

image

**Comment by JaceRiehl** [comment]
I agree, the 'Your Stacks' was removed in the UI redesign but I agree that we should remove the 'path selected'.

**Comment by johnanvik** [comment]
Either the dropbox needs to be more prominent, or can we have a grid where they can click on the one they want? The latter seems better as they can then see all the different options next to each other.

image

**Comment by johnanvik** [comment]
Make sure the timer is visible on the other two themes.

image

**Comment by JaceRiehl** [comment]
The timer was redone in the UI Redesign PR which is why I didn't touch it here

**Comment by johnanvik** [comment]
Should they select the theme from the start page? The button bars seems to be getting crowded. Maybe we need to start thinking of a menu that has all of these items instead.

**Comment by JaceRiehl** [comment]
Thats a good point. It would be a good idea to put them into a hamburger menu. Ill move it to the start page.

**Pull request merged**
