### PR TITLE
Add button only shows up when you can actually add

### LINKED ISSUE #46: Showing valid moves
Given the audience of the game, it could be helpful to indicate which cards are valid to be played on a stack. This would help the user avoid frustration by trying to make an illegal move.

### LINKED ISSUE #177: Hide "Add" for stacks that already have instructions
### I have an idea that might make the game better...

When an instruction card is selected, hide the "Add" buttons for other instruction piles as you can't stack instruction cards.

### PR DESCRIPTION
**Pull request by vincentcote87**
Fixes #177 and fix #46
#### Overview of changes

- The add to stack button will only appear when the selected card can be played on the stack.
- I have added #46 as a fix since it is showing valid moves only.

Reviewer: @johnanvik

### CODE REVIEW

**Comment by vincentcote87** [comment]
Yea it doesn't account for the different possible group. Helps kids with their math skills hehe.

**Comment by johnanvik** [comment]
I'm wondering if computing allowable groups will help with the AI?

For now, will approve and create an issue specific for groups.

**Comment by johnanvik** [comment]
Changed my mind about issue for groups. I think it will get too complex as there are so many different possibilities that could happen (1 stack, 2 stacks, 3 stacks...)

**Comment by vincentcote87** [comment]
Yea thats what I was thinking to as I will need to come up with a way to check for groups with ai.

**Pull request merged**
