### PR TITLE
Changed when it looks for winner

### LINKED ISSUE #64: Win conditions
Have win calculated at the coin flip to allow multiple winners. This removes the advantage of going first.

### PR DESCRIPTION
**Pull request by vincentcote87**
The game will now only check for winners at the end of each round, therefore giving every player a chance to get a high score. Currently doesn't deal with a tie, in case of a tie the first player to get the tie score will be declared winner but the score board will show the tie.

*Also fixed an error with the tips toggle when no card was active, behaves properly now.

fix #64 
#72 is no longer valid as the order does not give an advantage anymore.

### CODE REVIEW

**Comment by johnanvik** [comment]
Can you please resolve the conflict? I'm guessing it is related to the recent revert.

**Comment by vincentcote87** [comment]
Don't approve yet, something is off with the original coin flip animation. It won't stop spinning. Will push a commit soon.

**Comment by johnanvik** [comment]
(Big sigh) I reverted the reversion as Shawn installed the missing package. But now this is conflicted again. Sorry.

**Comment by vincentcote87** [comment]
No worries, I am implementing the check win on coin flip and adding a condition when there are multiple winners. Will resolve with next commit.

**Comment by vincentcote87** [comment]
Screen shrink is back with bringing back the revert... Looking into it.

**Comment by vincentcote87** [comment]
@johnanvik I believe it is finally ready to be looked at for approval... hopefully.

**Pull request merged**
