### PR TITLE
Card distribution

### PR DESCRIPTION
**Pull request by johnanvik**
I've changed to card distribution to be better for two player games.

@vincentcote87 try the new card distribution and see if you think it works better.

### CODE REVIEW

**Comment by vincentcote87** [comment]
I like the added Instruction cards, it definitely helps in being able to make moves right away. I think the number of Variable cards could go down as there are only 6 RepetitionX cards, maybe make up each Variable card removed with a normal Repetition card.

**Comment by johnanvik** [comment]
Changed the distribution of variable and repetition cards. See if that is better.

**Comment by vincentcote87** [comment]
I played a couple rounds with this configuration, I think it feels pretty good. Good paste of game (with two players at least).

**Comment by johnanvik** [comment]
Approved?

**Comment by vincentcote87** [comment]
Approved.

**Pull request merged**
